import Head from 'next/head'
import type { ReactElement } from 'react'
import Sidebar from '../Sidebar'

export default function MainLayout(page: ReactElement) {
  return <>
    <Head>
      <title>GPT Playground</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="h-screen flex">
      <Sidebar />
      <div className="flex-1">
        {page}
      </div>
    </main>
  </>
}
